# Primary Datasource
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Secondary Datasource
secondary.datasource.url=jdbc:h2:mem:testdb_secondary;DB_CLOSE_DELAY=-1
secondary.datasource.driverClassName=org.h2.Driver
secondary.datasource.username=sa
secondary.datasource.password=password

# Logging
logging.level.org.hibernate.SQL=trace
logging.level.com.ems=debug
